# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db1e6be68214403a5bc1fe7c2870924c"
name = "PixelMint Studio"
application_url = "https://example.com"
embedded = true
handle = "pixelmint-studio"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
